version: "3.5"

services:      
  apache:
    image: 'httpd:2.4.41-alpine'
    container_name: apache
    environment:
      - APACHE_HOST=${APACHE_HOST}
    build:
      context: .
      dockerfile: .docker/apache/Dockerfile
    volumes: 
      - ./etc/infrastructure/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:rw
      - ./etc/infrastructure/apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:rw
      - ./etc/infrastructure/ssl:/usr/local/apache2/ssl:delegated
      - ./index.php:/var/www/html/index.php
      - .:/var/www/html/bots/:delegated
    ports:
    - 80:80
    - 443:443
    depends_on:
      - php
    networks:
      - backend

  php:
    container_name: php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    restart: unless-stopped
    ports:
      - "9091:9001"
      - "9090:9000"
    volumes:
      - ./index.php:/var/www/html/index.php
      - .:/var/www/html/bots/:delegated
    networks:
      - backend

  redis: 
    container_name: redis
    image: 'redis:5.0.7-alpine'
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - backend

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend

networks:
    backend:
      name: backend